In [1]:
import numpy as np
import pandas as pd
import os
import cv2
# import labelencoder
from sklearn.preprocessing import LabelEncoder


In [2]:
le = LabelEncoder()

In [3]:
path = 'images'
folders = []
for folder in os.listdir(path):
    folders.append(folder)
print(folders)

['animal', 'deforestation', 'fire', 'forest']


In [4]:
# convert the folders list to array
folders = np.array(folders)
folders

array(['animal', 'deforestation', 'fire', 'forest'], dtype='<U13')

In [5]:
# Use Label Encoder to convert the folders name to numbers
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
labels = le.fit_transform(folders)

In [6]:
labels

array([0, 1, 2, 3], dtype=int64)

In [7]:
image_array = []
image_label = []

for i in folders:
    path = 'images/' + i
    for image in os.listdir(path):
        image = cv2.imread(path + '/' + image)
        image = cv2.resize(image, (64,64))
        # image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        image_array.append(image)
        image_label.append(le.transform([i])[0])

In [8]:
# image_array = []
# image_label = []

# for i in folders:
#     path = 'images/' + i
#     for image in os.listdir(path):
#         image = cv2.imread(path + '/' + image)
#         if image is None:
#             print(f"Failed to load image at {path + '/' + image}")
#             continue
#         image = cv2.resize(image, (24,24))
#         image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#         image_array.append(image)
#         image_label.append(le.transform([i])[0])


In [9]:
image_label

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [10]:
image_array = np.array(image_array)
image_label = np.array(image_label)


In [11]:
image_array = image_array.astype("float32")/255.0


In [12]:
# import train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(image_array, image_label, test_size = 0.2, random_state = 42)

In [13]:
import tensorflow as tf
# import layers, models
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
#import model
from tensorflow.keras.models import Sequential
from tensorflow.keras import models, layers

In [14]:
model = models.Sequential()

# Convolutional and max-pooling layers
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

# Dropout layer
model.add(layers.Dropout(0.5))

# Flatten layer
model.add(layers.Flatten())

# Dense layers
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))

# Output layer
model.add(layers.Dense(len(folders), activation='softmax'))  # num_classes is the number of classes you want to predict

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 62, 62, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 31, 31, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 29, 29, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 14, 14, 64)       0         
 2D)                                                             
                                                                 
 dropout (Dropout)           (None, 14, 14, 64)        0         
                                                                 
 flatten (Flatten)           (None, 12544)             0

In [15]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=20, validation_data=(x_test, y_test)) 

Epoch 1/20
29/29 [==============================] - 6s 158ms/step - loss: 1.0735 - accuracy: 0.5150 - val_loss: 0.8071 - val_accuracy: 0.6726
Epoch 2/20
29/29 [==============================] - 4s 142ms/step - loss: 0.7659 - accuracy: 0.6804 - val_loss: 1.3933 - val_accuracy: 0.5133
Epoch 3/20
29/29 [==============================] - 4s 144ms/step - loss: 0.7265 - accuracy: 0.7248 - val_loss: 0.6853 - val_accuracy: 0.7212
Epoch 4/20
29/29 [==============================] - 4s 142ms/step - loss: 0.5449 - accuracy: 0.8135 - val_loss: 0.6551 - val_accuracy: 0.7434
Epoch 5/20
29/29 [==============================] - 4s 146ms/step - loss: 0.4471 - accuracy: 0.8413 - val_loss: 0.5651 - val_accuracy: 0.7832
Epoch 6/20
29/29 [==============================] - 4s 144ms/step - loss: 0.3596 - accuracy: 0.8735 - val_loss: 0.5286 - val_accuracy: 0.8142
Epoch 7/20
29/29 [==============================] - 4s 144ms/step - loss: 0.3074 - accuracy: 0.9168 - val_loss: 0.5759 - val_accuracy: 0.8097
Epoch 

In [17]:
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_pred_classes

8/8 [==============================] - 0s 24ms/step


array([3, 3, 2, 0, 3, 2, 2, 1, 1, 0, 1, 2, 3, 1, 0, 1, 0, 1, 2, 1, 1, 2,
       2, 2, 1, 1, 3, 0, 0, 1, 1, 3, 1, 0, 1, 1, 1, 2, 2, 0, 2, 1, 3, 1,
       3, 3, 3, 0, 1, 0, 2, 2, 2, 0, 3, 0, 1, 2, 2, 0, 0, 0, 3, 1, 3, 0,
       2, 2, 0, 2, 2, 1, 2, 3, 1, 0, 1, 1, 0, 1, 1, 3, 2, 0, 3, 3, 2, 2,
       0, 1, 1, 0, 1, 1, 1, 0, 3, 0, 1, 1, 1, 2, 1, 3, 3, 3, 3, 1, 2, 3,
       2, 2, 1, 0, 0, 0, 2, 1, 2, 1, 2, 1, 0, 2, 1, 2, 2, 2, 1, 1, 2, 1,
       1, 0, 2, 3, 3, 1, 1, 1, 2, 0, 2, 1, 1, 2, 3, 3, 1, 3, 3, 2, 0, 0,
       1, 1, 0, 3, 3, 2, 1, 1, 3, 1, 3, 1, 0, 0, 2, 1, 0, 2, 2, 3, 3, 1,
       2, 0, 0, 3, 0, 0, 3, 1, 3, 2, 1, 3, 0, 1, 2, 2, 2, 2, 2, 1, 3, 0,
       3, 1, 0, 2, 0, 3, 0, 0, 3, 2, 0, 2, 2, 3, 1, 3, 2, 3, 3, 2, 0, 1,
       0, 1, 1, 0, 3, 2], dtype=int64)

In [19]:
x_test[0]

array([[[0.47843137, 0.44313726, 0.3647059 ],
        [0.49019608, 0.49019608, 0.4862745 ],
        [0.47058824, 0.47058824, 0.43137255],
        ...,
        [0.60784316, 0.7607843 , 0.88235295],
        [0.64705884, 0.78039217, 0.88235295],
        [0.5568628 , 0.654902  , 0.7411765 ]],

       [[0.47843137, 0.42745098, 0.34117648],
        [0.4862745 , 0.45882353, 0.4       ],
        [0.4745098 , 0.44705883, 0.37254903],
        ...,
        [0.5411765 , 0.78431374, 0.91764706],
        [0.5529412 , 0.78431374, 0.9019608 ],
        [0.54901963, 0.7294118 , 0.85490197]],

       [[0.45882353, 0.4117647 , 0.36078432],
        [0.44705883, 0.42745098, 0.3529412 ],
        [0.47058824, 0.42352942, 0.3529412 ],
        ...,
        [0.70980394, 0.9529412 , 1.        ],
        [0.6117647 , 0.87058824, 0.95686275],
        [0.7372549 , 0.95686275, 1.        ]],

       ...,

       [[0.06666667, 0.05882353, 0.05490196],
        [0.05882353, 0.05098039, 0.04705882],
        [0.05882353, 0

In [22]:
# single_image = # Assuming x_test[0] is a single image
single_image = np.expand_dims(x_test[0], axis=0)

# Make predictions with the model
predictions = model.predict(single_image)
print(predictions)
np.argmax(predictions[0])

1/1 [==============================] - 0s 38ms/step
[[2.4758454e-04 5.6659692e-04 2.3223794e-04 9.9895358e-01]]


3

In [ ]:
# Convert one-hot encoded labels to original labels
y_test_original = le.inverse_transform(y_test)
y_pred_original = le.inverse_transform(y_pred_classes)


In [ ]:
# import confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
cm = confusion_matrix(y_test_original, y_pred_original)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[41  5  4  4]
 [ 9 31  1 13]
 [ 4  0 61  0]
 [ 4  2  1 46]]


In [ ]:
# export the model
model.save('model2.h5')

In [ ]:
import tensorflow as tf

In [ ]:
# Convert the model to TensorFlow Lite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TensorFlow Lite model to a file
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

INFO:tensorflow:Assets written to: C:\Users\baral\AppData\Local\Temp\tmp01bc87dv\assets


INFO:tensorflow:Assets written to: C:\Users\baral\AppData\Local\Temp\tmp01bc87dv\assets


In [ ]:
video_capture = cv2.VideoCapture(0)